vqvae:
  # Encoder / Decoder
  in_channels: 3
  hidden_channels: [64, 128, 256]
  embedding_dim: 256
  
  # Codebook
  num_embeddings: 512
  commitment_cost: 0.25

  # Training
  learning_rate: 0.0002
  batch_size: 32
  num_epochs: 100
  num_workers: 0

  # Data
  image_dir: "data/images/elasticc_1/2grid"
  image_size: 256
  val_split: 0.1

  # Clasificación supervisada
  labels_path: "data/folds/labels.json"
  num_classes: 17
  cls_weight: 0.1
  cls_dropout: 0.1
  
  # Checkpoints
  checkpoint_dir: "results/vqvae/checkpoints_cls01"
  log_dir: "results/vqvae/logs"
